No CC_UNUSED_PARAM
cocos2d/cocos2d-x pull request #16812
Opened 2016-11-04 15:09 UTC by pyrosphere

In #16774 I tried to make cocos2d-x more consistent in the use of CC_UNUSED_PARAM but to keep the code more simple and cleaner it was suggested it might be better to just ignore this type of warning.

This PR adds the -Wno-unused-parameter (which is turned on in DEBUG with -Wextra) and removed all the uses of the macro CC_UNUSED_PARAM. The macro itself is kept as it might be in use by some game devs in their own code.

2016-11-07 01:19 UTC, stevetranby commented
@pyrosphere @minggo 

I think where possible you might want to just remove (or comment out) the parameter name from most or all of these instances of code where CC_UNUSED_PARAM was used before. 

The warning could then stay enabled to allow catching some subtle error in the future? 
```
void Action::step(float dt)
{
  CC_UNUSED_PARAM(dt);
  CCLOG("[Action step]. override me");
}
```
After
```
void Action::step(float /*dt*/) // or just `step(float)`
{
  CCLOG("[Action step]. override me");
}
```
* I prefer just removing the name because then any change to isn't more complicated by having to find it in the comments. And if you ever need to know the name to use it later one can just look at the header and add the name (which, honestly, should already be known since the name likely explains the usage).

2c

2016-11-07 01:22 UTC, stevetranby commented
It would not surprise me if there were issues that occur when not using the actual name, but it's the method I usually use if there's a good reason for the parameter to exist and yet there's not a usage of it within. YMMV

2016-11-07 01:57 UTC, minggo commented
@stevetranby the solution looks smart. @pyrosphere what's your opinion?

2016-11-07 02:10 UTC, stevetranby commented
The main issue reading all the changes would be the header files. The parameter names are probably necessary for Doxygen (not something we care about) and the use cases inside header files mostly in virtual base classes my suggestion might make it less clear.

It might be nice to reduce the warnings in the .cpp files, however. So you could keep the warning disabled by default, but if someone enables it briefly for testing or some other reason then they wouldn't see as many warnings??

2016-11-07 02:30 UTC, minggo commented
I am not sure if the parameter name in function decalaration is needed by Doxygen. I think Doxygen just need to parse `@param` section.

2016-11-07 10:45 UTC, pyrosphere commented
@minggo The solution @stevetranby suggests is a good one. I would prefer `step(float)` over `step(float /*dt*/)`, applied to .cpp files.

2016-11-07 12:37 UTC, pyrosphere commented
I checked the coding style doc and it says
> If some parameters are unused, comment out the variable name in the function definition
so /* var_name */ seems the best approach.

2016-11-07 22:26 UTC, stevetranby commented
One last concern would be issues with less helpful autocomplete.

Maybe all method declarations in header files and especially valid inline virtual methods that have an empty body block (which triggers the warning) should keep their actual parameter names for the purpose of autocomplete, etc?

Could also move non-inline methods into the .cpp files where appropriate since declarations don't trigger the warning, only definitions.

2016-11-08 01:35 UTC, minggo commented
Keep parameter name in header file is ok since it will not cause warning.

2016-11-09 01:33 UTC, minggo commented on cmake/Modules/SetCompilerOptions.cmake
> +	  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wno-deprecated-declarations -Wno-reorder -Wno-invalid-offsetof -Wno-unused-parameter -fPIC")
I think we don't need it since we fix warnings.

2016-11-09 01:35 UTC, minggo commented on cocos/2d/CCLayer.h
> +    CC_DEPRECATED_ATTRIBUTE virtual void ccTouchesCancelled(__Set *pTouches, Event *pEvent) final {}
these functions are defined in header files, i think we should move the definition into .cpp file.

2016-11-09 02:30 UTC, minggo commented on cocos/2d/CCLayer.h
> +    CC_DEPRECATED_ATTRIBUTE virtual void ccTouchesCancelled(__Set *pTouches, Event *pEvent) final {}
or we should comment the parmaters

2016-11-09 11:25 UTC, pyrosphere commented on cocos/2d/CCLayer.h
> +    CC_DEPRECATED_ATTRIBUTE virtual void ccTouchesCancelled(__Set *pTouches, Event *pEvent) final {}
I think the best approach is to move the definition to the .cpp and avoid commenting parameter names in headers.

2016-11-10 03:02 UTC, minggo commented on cocos/2d/CCNode.h
> +    virtual void setOpacityModifyRGB(bool value) {}
will it cause warning?

2016-11-10 03:02 UTC, minggo commented on cocos/2d/CCMenu.h
> +    virtual void setOpacityModifyRGB(bool bValue) override {}
will it cause warning?

2016-11-10 03:03 UTC, minggo commented on cocos/2d/CCTextFieldTTF.h
> -        CC_UNUSED_PARAM(nLen);
will it cause warning?

2016-11-10 03:06 UTC, minggo commented
@pyrosphere i found you just remove `CC_UNUSED_PARAM ` in some functions that are defined in header files, i think it will cause warnings. How about define these functions in corresponding cpp files?

2016-11-10 03:10 UTC, minggo commented
Keep parameter names in header files are needed to generate lua API files that [in this folder:](https://github.com/cocos2d/cocos2d-x/tree/v3/cocos/scripting/lua-bindings/auto/api). These files are used by code IDE for code completion. Code IDE is canceled, but i don't know if there is some developers need these files too, so i think it is better to keep as it is.

2016-11-14 01:42 UTC, minggo commented
@pyrosphere any updated?

2016-11-14 08:04 UTC, yahont commented
Please let me know when it's merged by commenting in #16838

2016-11-14 20:33 UTC, yahont requested changes

2016-11-14 20:33 UTC, yahont commented on cocos/2d/CCLayer.cpp
> -    CC_UNUSED_PARAM(acc);
acc is still unused if CC_ENABLE_SCRIPT_BINDING is false, it might be better too add the following at the end of the function:

```
#else
    CC_UNUSED_PARAM(acc);
#endif
```

2016-11-14 20:33 UTC, yahont commented on cocos/2d/CCLayer.cpp
> -    CC_UNUSED_PARAM(unused_event);
keyCode is unused if CC_ENABLE_SCRIPT_BINDING is false, it would be nice to have the following at the end of the function:

```
#else
    CC_UNUSED_PARAM(keyCode);
#endif
```

2016-11-14 20:33 UTC, yahont commented on cocos/2d/CCLayer.cpp
> -    CC_UNUSED_PARAM(event);
touch and event are unused if CC_ENABLE_SCRIPT_BINDING is false, it might be better to add the following at the end of the function:

```
#else
    CC_UNUSED_PARAM(touch);
    CC_UNUSED_PARAM(event);
#endif
```

2016-11-14 20:33 UTC, yahont commented on cocos/2d/CCLayer.cpp
> -    CC_UNUSED_PARAM(event);
```
#else
    CC_UNUSED_PARAM(event);
    CC_UNUSED_PARAM(touch);
#endif
```

2016-11-14 20:33 UTC, yahont commented on cocos/2d/CCLayer.cpp
>      }
```
#else
    CC_UNUSED_PARAM(event);
    CC_UNUSED_PARAM(touch);
```

2016-11-14 20:33 UTC, yahont commented on cocos/2d/CCLayer.cpp
> -    CC_UNUSED_PARAM(event);
```
#else
    CC_UNUSED_PARAM(event);
    CC_UNUSED_PARAM(touches);
#endif
```

2016-11-14 20:33 UTC, yahont commented on cocos/2d/CCLayer.cpp
> -    CC_UNUSED_PARAM(event);
```
#else
    CC_UNUSED_PARAM(event);
    CC_UNUSED_PARAM(touches);
#endif
```

2016-11-14 20:33 UTC, yahont commented on cocos/2d/CCLayer.cpp
> -    CC_UNUSED_PARAM(event);
```
#else
    CC_UNUSED_PARAM(event);
    CC_UNUSED_PARAM(touches);
#endif
```

2016-11-14 20:33 UTC, yahont commented on cocos/2d/CCLayer.cpp
> -    CC_UNUSED_PARAM(event);
```
#else
    CC_UNUSED_PARAM(event);
    CC_UNUSED_PARAM(touches);
#endif
```

2016-11-14 20:33 UTC, yahont commented on cocos/base/CCIMEDelegate.h
> +    virtual void insertText(const char * text, size_t len) {}
text and len should be commented out

2016-11-14 20:33 UTC, yahont commented on cocos/base/CCIMEDelegate.h
> +    virtual void keyboardWillShow(IMEKeyboardNotificationInfo& info)   {}
```
/*info*/
```

2016-11-14 20:33 UTC, yahont commented on cocos/base/CCIMEDelegate.h
> +    virtual void keyboardDidShow(IMEKeyboardNotificationInfo& info)    {}
```
/*info*/
```

2016-11-14 20:33 UTC, yahont commented on cocos/base/CCIMEDelegate.h
> +    virtual void keyboardWillHide(IMEKeyboardNotificationInfo& info)   {}
```
/*info*/
```

2016-11-14 20:33 UTC, yahont commented on cocos/base/CCIMEDelegate.h
> +    virtual void keyboardDidHide(IMEKeyboardNotificationInfo& info)    {}
```
/*info*/
```

2016-11-14 20:33 UTC, yahont commented on cocos/editor-support/cocostudio/CCInputDelegate.h
> +    CC_DEPRECATED_ATTRIBUTE virtual void didAccelerate(cocos2d::Acceleration* accelerationValue) final {};
```
/*accelerationValue*/
```

2016-11-14 20:33 UTC, yahont commented on cocos/editor-support/cocostudio/CCInputDelegate.h
> +    CC_DEPRECATED_ATTRIBUTE virtual bool ccTouchBegan(cocos2d::Touch *pTouch, cocos2d::Event *pEvent) final {return false;};
Shouldn't pTouch and pEvent be commented out?

2016-11-14 20:33 UTC, yahont commented on cocos/editor-support/cocostudio/CCInputDelegate.h
> +    CC_DEPRECATED_ATTRIBUTE virtual void ccTouchMoved(cocos2d::Touch *pTouch, cocos2d::Event *pEvent) final {}
Shouldn't pTouch and pEvent be commented out?

2016-11-14 20:33 UTC, yahont commented on cocos/editor-support/cocostudio/CCInputDelegate.h
> +    CC_DEPRECATED_ATTRIBUTE virtual void ccTouchEnded(cocos2d::Touch *pTouch, cocos2d::Event *pEvent) final {}
Shouldn't pTouch and pEvent be commented out?

2016-11-14 20:33 UTC, yahont commented on cocos/editor-support/cocostudio/CCInputDelegate.h
> +    CC_DEPRECATED_ATTRIBUTE virtual void ccTouchesCancelled(cocos2d::__Set *pTouches, cocos2d::Event *pEvent) final {}
Shouldn't pTouches and pEvent be commented out?

2016-11-14 20:33 UTC, yahont commented on cocos/editor-support/cocostudio/CCInputDelegate.h
> +    CC_DEPRECATED_ATTRIBUTE virtual void ccTouchesEnded(cocos2d::__Set *pTouches, cocos2d::Event *pEvent) final {}
Shouldn't pTouches and pEvent be commented out?

2016-11-15 01:53 UTC, minggo commented
Please fix the compiling error on linux
```
tests.dir/Classes/ExtensionsTest/ControlExtensionTest/CCControlSceneManager.cpp.o
../../../lib/libcocos2dInternal.a(CSLoader.cpp.o): In function `cocos2d::CSLoader::bindCallback(std::string const&, std::string const&, cocos2d::ui::Widget*, cocos2d::Node*)':
CSLoader.cpp:(.text+0x18e5): undefined reference to `typeinfo for cocostudio::WidgetCallBackHandlerProtocol'
../../../lib/libcocos2dInternal.a(CSLoader.cpp.o): In function `cocos2d::CSLoader::nodeWithFlatBuffers(flatbuffers::NodeTree const*, std::function<void (cocos2d::Ref*)> const&)':
CSLoader.cpp:(.text+0x6694): undefined reference to `typeinfo for cocostudio::WidgetCallBackHandlerProtocol'
../../../lib/libcocos2dInternal.a(CSLoader.cpp.o): In function `cocos2d::CSLoader::createNode(cocos2d::Data const&, std::function<void (cocos2d::Ref*)> const&)':
CSLoader.cpp:(.text+0x6e70): undefined reference to `typeinfo for cocostudio::WidgetCallBackHandlerProtocol'
../../../lib/libcocos2dInternal.a(CSLoader.cpp.o): In function `cocos2d::CSLoader::createNodeWithFlatBuffersFile(std::string const&, std::function<void (cocos2d::Ref*)> const&)':
CSLoader.cpp:(.text+0x7309): undefined reference to `typeinfo for cocostudio::WidgetCallBackHandlerProtocol'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/lua-tests/lua-tests] Error 1
make[1]: *** [tests/lua-tests/project/CMakeFiles/lua-tests.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
I will merge it when it passes CI.

2016-11-16 01:48 UTC, minggo commented
thanks

2016-11-16 01:48 UTC, merged