[Label] use freetype api to support bold
cocos2d/cocos2d-x pull request #17436
Opened 2017-03-03 10:10 UTC by treert

label enable blod use shadow to achive, so bold and outline can not using in same time.
![](https://cloud.githubusercontent.com/assets/4133961/23546881/8225655a-003c-11e7-973f-4b812347fd55.png)

use freetype api to support bold
![](https://cloud.githubusercontent.com/assets/4133961/23546902/916abe16-003c-11e7-9749-21e9e4dd87ad.png)

2017-03-07 03:24 UTC, minggo commented on cocos/2d/CCLabel.h
> +    void setBold(bool bold = true);
please don't use default parameter

2017-03-07 03:26 UTC, minggo commented
@zilongshanren could you please take a look?

2017-03-08 03:17 UTC, treert commented on cocos/2d/CCLabel.h
> +    void setBold(bool bold = true);
ok, i will modify it

2017-05-26 01:56 UTC, zilongshanren commented on cocos/2d/CCLabel.h
> +    void setBold(bool bold);
I suggest not providing another `setBold` API, we should replace the old Bold implementation for TTF.

2017-05-26 01:58 UTC, zilongshanren requested changes
We should replace the old bold implementation with the new one

2017-07-03 02:12 UTC, treert commented on cocos/2d/CCLabel.h
> +    void setBold(bool bold);
sorry for reply so later

2017-12-17 09:25 UTC, Dimon4eg commented
[ci rebuild]

2017-12-18 00:51 UTC, minggo commented
The error description is:

```
/home/travis/build/cocos2d/cocos2d-x/cocos/2d/CCFontFreeType.cpp: In member function ‘unsigned char* cocos2d::FontFreeType::getGlyphBitmapWithOutline(uint64_t, FT_BBox&)’:

/home/travis/build/cocos2d/cocos2d-x/cocos/2d/CCFontFreeType.cpp:447:68: error: ‘FT_Outline_EmboldenXY’ was not declared in this scope

                         FT_Outline_EmboldenXY(outline, _boldSize, 0);

                                                                    ^

make[2]: *** [cocos/CMakeFiles/cocos2dInternal.dir/2d/CCFontFreeType.cpp.o] Error 1

make[1]: *** [cocos/CMakeFiles/cocos2dInternal.dir/all] Error 2
```

2017-12-25 10:06 UTC, drelaptop requested changes
Thank you for this good feature. it works well on macOS when I tested. meanwhile I have some suggestions to improve this PR, I found that after I read your code again and again. 

sorry for a long response. @treert

2017-12-25 10:06 UTC, drelaptop commented on cocos/2d/CCLabel.cpp
> -        this->enableBold();
This PR is another better implementation of `support bold for TTF font`, but two lines above is the logic of enable bold for label. so I think they shouldn't been removed, for those are reasonable, intuitive and easy to understand.

2017-12-25 10:06 UTC, drelaptop commented on cocos/2d/CCLabel.cpp
>                  _boldEnabled = false;
code in `Label::enableBold()` changed the meaning of __`_boldEnabled`__ ,  because `_boldEnabled = false` when a TTF label enable bold, that is strange. 

We should keep `_boldEnabled` true as long as a label enables bold.  In order to achieve this goal, we can put `if (_currentLabelType == LabelType::TTF)` in `if (!_boldEnabled)`.

2017-12-25 10:06 UTC, drelaptop commented on cocos/2d/CCFontFreeType.cpp
> +        tempFont->_boldSize = CC_CONTENT_SCALE_FACTOR() * 64;
__64__ is a magic number, it's difficult to understand the meaning. using this way:`#define TIME_DELAY_PRECISION 0.0001` is better.

2017-12-26 01:53 UTC, drelaptop commented
one more things, we should rich test case, like below rich case existed,:
```C++
LabelOutlineAndGlowTest::LabelOutlineAndGlowTest()
{
    ...
    
    ttfConfig.outlineSize = 3;
    auto label5 = Label::createWithTTF(ttfConfig,"Outline and Bold", TextHAlignment::CENTER, size.width);
    label5->setPosition( Vec2(size.width/2, size.height*0.24) );
    label5->setTextColor( Color4B::RED );
    label5->enableOutline(Color4B::BLUE);
    label5->enableBold();
    addChild(label5);
}
```
another way is create a new case, and add it into `LabelTestNew` to test this feature.

2021-03-18 01:28 UTC, closed without merging

2021-03-18 01:29 UTC, treert commented
drelaptop 完善测试后，发现只加粗不描边情况下显示不好。
https://github.com/cocos2d/cocos2d-x/pull/18598