fix keyback bug after opened a page
cocos2d/cocos2d-x pull request #18153
Opened 2017-08-11 05:36 UTC by Sevellion

bug happen when:
1.implement keyback in a scene
2.implement webview in that scene and load a default URL
3.click any link and wait for it to load
4.press key back, the implemented keyback will not be called

2017-08-22 01:38 UTC, minggo commented
could you please add a test case for it, thanks.

2017-12-06 09:17 UTC, drelaptop requested changes

2017-12-06 09:17 UTC, drelaptop commented on cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxWebView.java
> +        this.setFocusableInTouchMode(false);
The issue you described is existed, and your changes fix the issue, but it has a bad effect on others. 
when you set `this.setFocusableInTouchMode(false);`, some item in WebView can't get focus. For example load url `https://www.baidu.com`, the search bar can't  get focus when you touch on it.

2017-12-28 03:37 UTC, drelaptop commented
this PR solved a issue, but caused other issues. Meanwhile author didn't response for a long time, I suggest to close this PR. @minggo

2018-01-02 02:37 UTC, merged