18572 PR amends & override warning fix
cocos2d/cocos2d-x pull request #18580
Opened 2017-12-19 17:17 UTC by kaplad

1. Apply comments from [#18572 PR](https://github.com/cocos2d/cocos2d-x/commit/4c0361e1842b046be6e29eac367ec019424df74a#commitcomment-26363558)
2. Remove `override` warning mentioned in  [#18578](https://github.com/cocos2d/cocos2d-x/issues/18578) issue

2017-12-20 01:37 UTC, drelaptop commented
@summerinsects thanks for your review before, the author have simplified  code, and why suggest to modify `EditBoxImplCommon::applyPadding` to static local function, will you explain for us?

2017-12-20 01:55 UTC, summerinsects commented
because `applyPadding` has nothing to do with any member variables or functions, it just related to CC_EDIT_BOX_PADDING.
so, I think it can be modified to static local function or static member function

2017-12-20 10:07 UTC, drelaptop requested changes

2017-12-20 10:07 UTC, drelaptop commented on cocos/ui/UIEditBox/UIEditBoxImpl-common.cpp
>  Size ui::EditBoxImplCommon::applyPadding(const Size& sizeToCorrect) const {
after the discuss, I think make it to __static local function__ is better, it has less space occupy when existing more than one EditBox, and have no outer effect.  you could refer to `static Rect getRect(Node * pNode)` in `UIEditBox.cpp`, both are similar.

2017-12-23 17:26 UTC, summerinsects commented
Can this pr fix another bug together?
add `refreshLabelAlignment();` in `setTextHorizontalAlignment` 
```c++
void EditBoxImplCommon::setTextHorizontalAlignment(cocos2d::TextHAlignment alignment)
{
    _alignment = alignment;
    this->setNativeTextHorizontalAlignment(alignment);
    refreshLabelAlignment();  // add this line
}
```

How to reduce: call `setTextHorizontalAlignment` after `setText` i.e.
```
editBox->setText("text");
editBox->setTextHorizontalAlignment(TextHAlignment::CENTER);
```

2017-12-25 03:59 UTC, drelaptop commented
tested again, it truly fix a bug, we can rich the test case by adding code into `UIEditBoxTestTextHorizontalAlignment::init()`, like this:
```C++
        editPassword->setText("text alignment center");
        editPassword->setTextHorizontalAlignment(TextHAlignment::CENTER);
        editEmail->setText("text alignment right");
        editEmail->setTextHorizontalAlignment(TextHAlignment::RIGHT);
```
would you like add this changes to your PR?  @kaplad

2017-12-29 10:07 UTC, kaplad commented
Yeah, sure! @drelaptop
Sorry for late answer...very long Christmas holidays :D Will do that in a week

2018-01-06 20:48 UTC, kaplad commented
@drelaptop done ;)

2018-01-07 15:26 UTC, drelaptop commented
see the AppVeyor log, check your code please
```
       "C:\projects\cocos2d-x\build\cocos2d-win32.sln" (Build target) (1) ->
       "C:\projects\cocos2d-x\tests\cpp-tests\proj.win32\cpp-tests.vcxproj" (default target) (2) ->
       (ClCompile target) -> 
         ..\Classes\UITest\CocoStudioGUITest\UIEditBoxTest.cpp(322): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\projects\cocos2d-x\tests\cpp-tests\proj.win32\cpp-tests.vcxproj]
         ..\Classes\UITest\CocoStudioGUITest\UIEditBoxTest.cpp(322): error C2146: syntax error: missing ')' before identifier 'position_y' [C:\projects\cocos2d-x\tests\cpp-tests\proj.win32\cpp-tests.vcxproj]
         ..\Classes\UITest\CocoStudioGUITest\UIEditBoxTest.cpp(322): error C3260: 'identifier': skipping unexpected token(s) before lambda body [C:\projects\cocos2d-x\tests\cpp-tests\proj.win32\cpp-tests.vcxproj]
         ..\Classes\UITest\CocoStudioGUITest\UIEditBoxTest.cpp(324): error C2065: 'position_y': undeclared identifier [C:\projects\cocos2d-x\tests\cpp-tests\proj.win32\cpp-tests.vcxproj]
    2717 Warning(s)
    4 Error(s)
Time Elapsed 00:27:17.37
ScriptHalted
```

2018-01-08 13:05 UTC, kaplad commented
>The job exceeded the maximum time limit for jobs, and has been terminated

@drelaptop what I can do with that?

2018-01-08 13:12 UTC, drelaptop approved these changes
nothing we can do to solve maximum time, thanks for this patch @kaplad 

please merge @minggo

2018-01-09 01:26 UTC, merged