Fix no-brake space size
cocos2d/cocos2d-x pull request #18661
Opened 2018-01-27 18:32 UTC by Dimon4eg

Some fonts have an issue with no-break space:

- no letter definition
- not normal big width

Added test to reproduce the issue:
![image](https://user-images.githubusercontent.com/1271541/35475080-c33477bc-03a0-11e8-8cb1-c14f25a38518.png)

After fix:
![image](https://user-images.githubusercontent.com/1271541/35475050-5279d7e2-03a0-11e8-9364-72f1b03d7d73.png)

2018-02-10 23:00 UTC, Dimon4eg commented
[ci build]

2018-02-10 23:01 UTC, Dimon4eg commented
[ci rebuild]

2018-02-11 04:54 UTC, Dimon4eg commented
@minggo how to rebuild?

2018-02-11 05:38 UTC, drelaptop commented
have rebuild CI for you

2018-02-11 05:40 UTC, Dimon4eg commented
@drelaptop can I rebuild by self and if can then how?

2018-02-11 06:38 UTC, drelaptop commented
AFAIK, the CI will be rebuild after a commit, and a member of cocos team have the right to rebuild too. but I didn't know the travis CI have this feature that rebuild when get a new comment like `[ci rebuild]`

2018-03-09 01:56 UTC, drelaptop commented
[ci rebuild]

2018-03-09 03:06 UTC, drelaptop requested changes

2018-03-09 03:06 UTC, drelaptop commented on cocos/base/ccUTF8.cpp
> +        else if (nret > (int)buffer.length()) { // VS2015/2017 or later Visual Studio Version
it's not a good type conversion when compare `int` and `unsigned int`, convert `unsigned ` to `signed` might  cause negative value. when the int value `nret >= 0`, convert it to `signed` always right.

so I think `(unsigned int)nret > buffer.length()` is a better choice

2018-03-09 03:10 UTC, drelaptop commented
Thanks for this good patch @Dimon4eg. It works well when I tested on macOS and Android, little suggestion have commented, hope your feedback.

2018-03-09 09:22 UTC, Dimon4eg commented
Corrected, thank you @drelaptop

2018-03-12 09:56 UTC, drelaptop commented
review and test pass, please merge @minggo

2018-03-13 01:40 UTC, merged