Rewrite websocket
cocos2d/cocos2d-x pull request #19025
Opened 2018-09-07 08:10 UTC by PatriceJiang

rewrite websocket code

2018-09-09 20:33 UTC, crazyhappygame requested changes

2018-09-09 20:33 UTC, crazyhappygame commented on cocos/base/loop/Looper.h
> +                SeqItem<LoopEvent> item = _pendingEvents.popFront();
Why there is no lock here and there is lock in while loop above?

2018-09-09 20:33 UTC, crazyhappygame commented on cocos/base/loop/Collections.h
> +            size_t size() const { return _data.size(); }
why size without lock?

2018-09-09 20:33 UTC, crazyhappygame commented on cocos/base/loop/Looper.h
> +                std::condition_variable cv;
Could you explain this part o code?
What is a point tocreate local mutex conditional variable lock and than pass reference and than wait?
It seems like when wait_for will expire we may have rice condition

2018-09-10 01:11 UTC, PatriceJiang commented on cocos/base/loop/Looper.h
> +                SeqItem<LoopEvent> item = _pendingEvents.popFront();
`popFront` will be invoked only in `onNotify()`, one threaded. `item` will not be modified.

2018-09-10 01:17 UTC, PatriceJiang commented on cocos/base/loop/Collections.h
> +            size_t size() const { return _data.size(); }
`size()` itself is threadsafe, lock make no point here.

2018-09-10 01:35 UTC, PatriceJiang commented on cocos/base/loop/Looper.h
> +                std::condition_variable cv;
`lock2` is not used, I will drop it.

2018-09-10 02:25 UTC, PatriceJiang commented on cocos/base/loop/Looper.h
> +                std::condition_variable cv;
>It seems like when wait_for will expire we may have rice condition.

 yes. main thread should not be frozen forever even if it happens, and timeout value should be chosen properly.

2018-09-10 12:32 UTC, crazyhappygame requested changes

2018-09-10 12:32 UTC, crazyhappygame commented on cocos/base/loop/Collections.h
> +            size_t size() const { return _data.size(); }
No, size of std::list (and any other and container) is not thread safe.
If in thread1 size is changed and thread2 check size this is race condition.

2018-09-10 12:41 UTC, crazyhappygame requested changes

2018-09-10 12:41 UTC, crazyhappygame commented on cocos/base/loop/Looper.h
> +                std::condition_variable cv;
I am do sorry I do not understand it....
Why we need mutex mtx as local function variable?

2018-09-10 12:41 UTC, crazyhappygame commented on cocos/base/loop/Looper.h
> +                SeqItem<LoopEvent> item = _pendingEvents.popFront();
problem is with size.
Size is not thread safe

2018-09-11 01:18 UTC, PatriceJiang commented on cocos/base/loop/Looper.h
> +                SeqItem<LoopEvent> item = _pendingEvents.popFront();
`size()` returns `size_t` value, it is 32-bits wide on 32-bits platform and 64-bits wide on 64-bits platform. 
single read (or write) is an atomic operation.

2018-09-11 01:24 UTC, PatriceJiang commented on cocos/base/loop/Collections.h
> +            size_t size() const { return _data.size(); }
add lock inside `size()` dose not help.

2018-09-11 01:38 UTC, PatriceJiang commented on cocos/base/loop/Looper.h
> +                std::condition_variable cv;
the mutex is used in `cv.wait` and it will only be invoked once locally.

2018-09-11 03:54 UTC, crazyhappygame commented on cocos/base/loop/Looper.h
> +                SeqItem<LoopEvent> item = _pendingEvents.popFront();
That was (maybe) true in past for single core processors. Currently with mulitocore processors with multiple level or caches it is not true any more. E.g. without mutex second thread(on second core) may not see that size was changed

2018-09-11 19:40 UTC, crazyhappygame requested changes
@minggo @PatriceJiang I did not spend much time on review but current implementation have many threads problems. Such problems are hard to reproduce fix and debug ....

I think that even if we fix all those problems we will have code which is much more complicated than current implementation with more or less the same number of locks and atomics and performance problems...

Please double check current implementation. All variables (even bools and integers) must be protected by mutex (or change to atomic) if there is at least one write/update in multi-threaded code.

I checked current WebSocket.cpp and I think is much simpler to understand what's going on than this PR. 

Instead of rewriting everything I propose to fix/simplify current WebSocket.cpp implementation. 
uv is very nice library but I doubt if it fix all our current poblems.

2018-09-11 19:40 UTC, crazyhappygame commented on cocos/base/loop/LoopRunable.h
> +            int64_t _intervalMS = 3000LL;
Pleas use std::chrono here and in any other places when time/duration is used

2018-09-11 19:40 UTC, crazyhappygame commented on cocos/base/loop/Looper.h
> +#if defined(__GNUC__)
Why this is needed

2018-09-11 19:40 UTC, crazyhappygame commented on cocos/base/loop/Looper.h
> +                std::condition_variable cv;
1. But why for timeoutMS==0 add something to _pendingFns in thread1 and than wait inside thread1 until thread2 will finish?
2. For timeoutMS>0 is when cv.wait_for(lock, milliseconds(timeoutMS)); will expire than std::condition_variable cv; but cv is passed as reference to lambda [&cv  this is crash/undefined behaviur....

2018-09-11 19:40 UTC, crazyhappygame commented on cocos/base/loop/Looper.h
> +                SeqItem<LoopEvent> item = _pendingEvents.popFront();
1. OK. Size is fixed. Thank you! By the way e.g. here is https://baptiste-wicht.com/posts/2012/03/cp11-concurrency-tutorial-part-2-protect-shared-data.html there is simple example which you can run multiple times and see that int is really not atomic 
2. But I see another problem 
```
while(_pendingEvents.size() > 0)
//Between those two lines another thread may add remove item from  _pendingEvents and we have undefined behavior
SeqItem<LoopEvent> item = _pendingEvents.popFront();
```

2018-09-11 19:40 UTC, crazyhappygame commented on cocos/base/loop/Looper.h
> +            bool _forceStoped = false;
I think all those members should be changed to atomic protected by mutex

2018-09-12 01:07 UTC, minggo commented
@crazyhappygame ok, i will take more time on this PR. The biggest purpose of this PR is simplify the codes and make it more safe. If you think it is more complex, then it may have problem.

2018-09-12 01:56 UTC, PatriceJiang commented on cocos/base/loop/Looper.h
> +                std::condition_variable cv;
my fault, I will use shared_ptr to protect `cv`

2018-10-12 03:41 UTC, PatriceJiang commented
It is too complicated and risky, so closed.

2018-10-12 03:41 UTC, closed without merging