Added md5 message digest function to encrypt strings.
cocos2d/cocos2d-x pull request #19274
Opened 2019-01-03 02:29 UTC by EricDDK

This is a function of encrypting strings, generally used for message digests and checksum data.

2019-01-04 07:01 UTC, PatriceJiang commented on cocos/base/ccUtils.h
> +	CC_DLL std::string getStringMD5Hash(const std::string &dataStr);
Please fix the code alignment

2019-01-04 07:04 UTC, PatriceJiang commented
You can rebase the change on to the recent v3 branch since the commit log is not brief.

![Uploading Screen Shot 2019-01-04 at 3.02.11 PM.png…]()

2019-01-07 08:32 UTC, Dimon4eg requested changes

2019-01-07 08:32 UTC, Dimon4eg commented on cocos/ui/UIImageView.h
> +	const std::string getTextureFile()const;
better to return const reference not just const

2019-01-07 09:33 UTC, halx99 commented on cocos/ui/UIImageView.cpp
> +const std::string ImageView::getTextureFile()const
No need const qualifier for non-reference result type.

2019-02-18 06:13 UTC, closed without merging