If path to file is tool long crash is possible.
cocos2d/cocos2d-x pull request #19383
Opened 2019-02-04 12:13 UTC by sbrednikhin

If path to file is tool long crash is possible, because of chart buffer overflow.

2019-02-04 12:14 UTC, sbrednikhin commented
Usage of stringstream instead of snprintf is possible, and maybe it would be even better, but I don't want to break something. Is this formatting is really required?

2019-02-04 18:37 UTC, Dimon4eg requested changes

2019-02-04 18:37 UTC, Dimon4eg commented on cocos/2d/CCFontAtlasCache.cpp
> +        return _atlasMap[atlasName];
> return _atlasMap[atlasName];

Why you changed this?

2019-02-04 18:38 UTC, Dimon4eg commented
In general looks ok.
About `stringstream`, better to avoid it because it's slow.

2019-02-05 07:25 UTC, sbrednikhin commented on cocos/2d/CCFontAtlasCache.cpp
> +        return _atlasMap[atlasName];
Looks like I was not very attentive, thank you for pointing. I'll change that immediately.

2019-02-05 07:40 UTC, Dimon4eg approved these changes

2019-02-05 07:41 UTC, Dimon4eg commented
Thank you

2019-02-13 02:00 UTC, minggo commented on cocos/2d/CCFontAtlasCache.cpp
> +    char key_prefix[ATLAS_MAP_KEY_PREFIX_BUFFER_SIZE];
key_prefix -> keyPrefix?

2019-02-13 02:00 UTC, minggo commented on cocos/2d/CCFontAtlasCache.cpp
> +    char key_prefix[ATLAS_MAP_KEY_PREFIX_BUFFER_SIZE];
As other variables uses this style.

2019-02-13 02:01 UTC, minggo commented on cocos/2d/CCFontAtlasCache.cpp
> +    char tmp[ATLAS_MAP_KEY_PREFIX_BUFFER_SIZE];
tmp -> keyPrefix?

2019-02-13 08:36 UTC, minggo approved these changes

2019-02-14 06:15 UTC, merged

2019-04-10 03:59 UTC, minggo commented
it is synchronized to metal-support branch in https://github.com/cocos2d/cocos2d-x/pull/19593